version: "3.8"
services:
    web:
        image: rsnstkw/web
        deploy:
            replicas: 3
        ports:
            - 8080:80
        volumes:
            - /home/vagrant/web-db/web:/var/www/html:ro
        networks:
            - app-network
    db:
        image: rsnstkw/db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: 12345
networks:
    app-network:
